"""The typed surface of ``hypertabular._native``, the PyO3 extension (``tests/test_typing.py``
holds the loaded module to this file). ``hypertabular`` re-exports all of it directly, so
this is what a type checker sees behind a reader, a batch and a column — and behind a cell,
which is HyperCast's own ``Success[...] | Fault``, so a ``match`` over the two cases can be
checked for exhaustiveness with ``typing.assert_never``.
"""

from collections.abc import Coroutine, Iterable, Iterator, Sequence
from os import PathLike
from typing import Any, ClassVar, Protocol, final

from hypercast import ExcelEpoch, Fault, Success

from . import (
    Column,
    Dialect,
    Header,
    SheetOptions,
    TabularError,
    TabularFailure,
    WorkbookFormat,
)
from ._aio import AsyncReadable

class _Readable(Protocol):
    def read(self, size: int, /) -> bytes: ...

@final
class ColumnData:
    @property
    def column(self) -> Column: ...
    @property
    def values(self) -> Sequence[Any]: ...
    @property
    def verdicts(self) -> memoryview: ...
    @property
    def fault_count(self) -> int: ...
    def faults(self) -> list[tuple[int, Fault]]: ...
    def raw(self, row: int) -> bytes: ...
    def __len__(self) -> int: ...
    def __getitem__(self, row: int) -> Success[Any] | Fault: ...
    def __iter__(self) -> Iterator[Success[Any] | Fault]: ...

@final
class Batch:
    @property
    def rows(self) -> int: ...
    @property
    def columns(self) -> tuple[ColumnData, ...]: ...
    def column(self, index: int) -> ColumnData: ...
    def line(self, row: int) -> int: ...
    def raw(self, column: int, row: int) -> bytes: ...
    def get(self, column: int, row: int) -> Success[Any] | Fault: ...
    def text(self, column: int, row: int) -> str | None: ...
    def row(self, row: int) -> Row: ...
    def iter_rows(self) -> Rows: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Rows: ...

@final
class Row:
    @property
    def index(self) -> int: ...
    @property
    def line(self) -> int: ...
    @property
    def batch(self) -> Batch: ...
    def get(self, column: int) -> Success[Any] | Fault: ...
    def text(self, column: int) -> str | None: ...
    def raw(self, column: int) -> bytes: ...
    def __len__(self) -> int: ...

@final
class Rows:
    def __iter__(self) -> Rows: ...
    def __next__(self) -> Row: ...

@final
class DelimitedReader:
    DEFAULT_BATCH_ROWS: ClassVar[int]
    DEFAULT_BUFFER_BYTES: ClassVar[int]
    MAX_ROW_BYTES: ClassVar[int]
    def __new__(
        cls,
        source: bytes | _Readable,
        dialect: Dialect,
        plan: Iterable[Column] | None = None,
        *,
        batch_rows: int = 4096,
        buffer_bytes: int = 262144,
    ) -> DelimitedReader: ...
    @staticmethod
    def open(
        path: str | PathLike[str],
        dialect: Dialect,
        plan: Iterable[Column] | None = None,
        *,
        batch_rows: int = 4096,
        buffer_bytes: int = 262144,
    ) -> DelimitedReader: ...
    @staticmethod
    def open_async(
        stream: AsyncReadable | bytes,
        dialect: Dialect,
        plan: Iterable[Column] | None = None,
        *,
        batch_rows: int = 4096,
        buffer_bytes: int = 262144,
    ) -> Coroutine[Any, Any, DelimitedReader]: ...
    @staticmethod
    def _over_async(
        stream: AsyncReadable | bytes,
        dialect: Dialect,
        plan: Iterable[Column] | None,
        batch_rows: int,
        buffer_bytes: int,
    ) -> DelimitedReader: ...
    def _advance(self) -> Batch | int | None: ...
    def _header(self) -> int | None: ...
    def _feed(self, chunk: bytes) -> None: ...
    def bind(self, plan: Iterable[Column]) -> None: ...
    @property
    def is_bound(self) -> bool: ...
    @property
    def header(self) -> Header | None: ...
    @property
    def column_count(self) -> int | None: ...
    @property
    def dialect(self) -> Dialect: ...
    @property
    def plan(self) -> tuple[Column, ...]: ...
    @property
    def batch_rows(self) -> int: ...
    @property
    def records(self) -> int: ...
    def read(self) -> Batch | None: ...
    def read_async(self) -> Coroutine[Any, Any, Batch | None]: ...
    def rows(self) -> Rows: ...
    def close(self) -> None: ...
    def __iter__(self) -> DelimitedReader: ...
    def __next__(self) -> Batch: ...
    def __aiter__(self) -> DelimitedReader: ...
    def __anext__(self) -> Coroutine[Any, Any, Batch]: ...
    def __enter__(self) -> DelimitedReader: ...
    def __exit__(self, *_exc: object) -> None: ...

@final
class SheetInfo:
    @property
    def name(self) -> str: ...
    @property
    def hidden(self) -> bool: ...

@final
class Workbook:
    def __new__(cls, data: bytes | _Readable) -> Workbook: ...
    @staticmethod
    def open(path: str | PathLike[str]) -> Workbook: ...
    @staticmethod
    def open_async(stream: AsyncReadable) -> Coroutine[Any, Any, Workbook]: ...
    @staticmethod
    def _from_chunks(chunks: Iterable[bytes]) -> Workbook: ...
    @property
    def format(self) -> WorkbookFormat: ...
    @property
    def date_system(self) -> ExcelEpoch: ...
    @property
    def sheets(self) -> tuple[SheetInfo, ...]: ...
    def sheet(
        self, which: int | str, options: SheetOptions, plan: Iterable[Column] | None = None
    ) -> Sheet: ...

@final
class Sheet:
    @property
    def options(self) -> SheetOptions: ...
    @property
    def plan(self) -> tuple[Column, ...]: ...
    @property
    def header(self) -> Header | None: ...
    def bind(self, plan: Iterable[Column]) -> None: ...
    @property
    def is_bound(self) -> bool: ...
    def read(self) -> Batch | None: ...
    def rows(self) -> Rows: ...
    def __iter__(self) -> Sheet: ...
    def __next__(self) -> Batch: ...

def native_version() -> str: ...
def _bind(
    column: type[Column],
    dialect: type[Dialect],
    error: type[TabularError],
    failure: type[TabularFailure],
    workbook_format: type[WorkbookFormat],
    header: type[Header],
) -> None: ...
def _limits(reader: DelimitedReader, max_row_bytes: int, window_bytes: int) -> None: ...
