"""The typed surface of ``hypertabular._native``, the PyO3 extension (``tests/test_typing.py``
holds the loaded module to this file). ``hypertabular`` re-exports all of it directly, so
this is what a type checker sees behind a reader, a batch and a column — and behind a cell,
which is HyperCast's own ``Success[...] | Fault``, so a ``match`` over the two cases can be
checked for exhaustiveness with ``typing.assert_never``.
"""

from collections.abc import Iterable, Iterator, Sequence
from os import PathLike
from typing import Any, ClassVar, Protocol, final

from hypercast import Fault, Success

from . import Column, Dialect, TabularError, TabularFailure

class _Readable(Protocol):
    def read(self, size: int, /) -> bytes: ...

@final
class ColumnData:
    @property
    def column(self) -> Column: ...
    @property
    def values(self) -> Sequence[Any]: ...
    @property
    def verdicts(self) -> memoryview: ...
    @property
    def fault_count(self) -> int: ...
    def faults(self) -> list[tuple[int, Fault]]: ...
    def raw(self, row: int) -> bytes: ...
    def __len__(self) -> int: ...
    def __getitem__(self, row: int) -> Success[Any] | Fault: ...
    def __iter__(self) -> Iterator[Success[Any] | Fault]: ...

@final
class Batch:
    @property
    def rows(self) -> int: ...
    @property
    def columns(self) -> tuple[ColumnData, ...]: ...
    def column(self, index: int) -> ColumnData: ...
    def raw(self, column: int, row: int) -> bytes: ...
    def __len__(self) -> int: ...

@final
class DelimitedReader:
    DEFAULT_BATCH_ROWS: ClassVar[int]
    DEFAULT_BUFFER_BYTES: ClassVar[int]
    MAX_ROW_BYTES: ClassVar[int]
    def __new__(
        cls,
        source: bytes | _Readable,
        dialect: Dialect,
        plan: Iterable[Column],
        *,
        batch_rows: int = 4096,
        buffer_bytes: int = 262144,
    ) -> DelimitedReader: ...
    @staticmethod
    def open(
        path: str | PathLike[str],
        dialect: Dialect,
        plan: Iterable[Column],
        *,
        batch_rows: int = 4096,
        buffer_bytes: int = 262144,
    ) -> DelimitedReader: ...
    @property
    def header(self) -> tuple[str, ...] | None: ...
    @property
    def dialect(self) -> Dialect: ...
    @property
    def plan(self) -> tuple[Column, ...]: ...
    @property
    def batch_rows(self) -> int: ...
    @property
    def records(self) -> int: ...
    def read(self) -> Batch | None: ...
    def close(self) -> None: ...
    def __iter__(self) -> DelimitedReader: ...
    def __next__(self) -> Batch: ...
    def __enter__(self) -> DelimitedReader: ...
    def __exit__(self, *_exc: object) -> None: ...

def native_version() -> str: ...
def _bind(
    column: type[Column],
    dialect: type[Dialect],
    error: type[TabularError],
    failure: type[TabularFailure],
) -> None: ...
def _limits(reader: DelimitedReader, max_row_bytes: int, window_bytes: int) -> None: ...
